Solved test book and category
Krasnov-Maksim/Online-Book-Store pull request #14
Opened 2024-02-09 11:11 UTC by Krasnov-Maksim

2024-02-09 16:02 UTC, kerrrusha requested changes

2024-02-09 16:02 UTC, koval-kn commented on pom.xml
not implemented:
Please add a screenshot with the test coverage result into the PR description

2024-02-09 16:02 UTC, kerrrusha commented on src/test/java/mate/academy/bookstore/controller/BookControllerIntegrationTest.java
> +    private ObjectMapper objectMapper;
jsonpath can be used instead to check response values:
`.andExpect(jsonPath("$.id").value(1))`
```suggestion
```
fix this in the whole project

2024-02-09 16:02 UTC, kerrrusha commented on pom.xml
why your PR contains changes not related with tests?

2024-02-09 22:51 UTC, Krasnov-Maksim commented
![Capture](https://github.com/Krasnov-Maksim/Online-Book-Store/assets/106538223/eb9b49c8-9fa7-4275-a2ad-d9ad41894d16)

2024-02-10 14:55 UTC, kerrrusha approved these changes

2024-02-10 15:56 UTC, merged