Solved global exception handler and data validation
Krasnov-Maksim/Online-Book-Store pull request #5
Opened 2023-12-18 13:47 UTC by Krasnov-Maksim

2023-12-18 18:22 UTC, sokimaaa commented on src/main/java/mate/academy/bookstore/validation/CreateBookRequestDtoValidator.java
> +    }
you dont need this. 

you can use @NotNull, @PositiveOrZero and so on.

2023-12-19 11:30 UTC, Sanderfuck requested changes

2023-12-19 11:30 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>          String isbn,
Valid isbn

2023-12-19 11:30 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>          String description,
You can valid description

2023-12-19 11:30 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("errors", errors);
Why you don`t add timestamp?

2023-12-19 18:53 UTC, Sanderfuck requested changes

2023-12-19 18:53 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>          String description,
You can valid more, by size, etc

2023-12-19 18:53 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>          String isbn,
You can create your own validation annotation for isbn

2023-12-19 18:53 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
> +        @NotNull
Do you need not null here anymore?

2023-12-20 13:57 UTC, kerrrusha approved these changes

2023-12-20 13:57 UTC, kerrrusha commented on src/main/java/mate/academy/bookstore/validation/IsbnValidator.java
> +    private static final int Isbn13Length = 13;
constants should be uppercased

2023-12-20 14:13 UTC, merged